In [3]:
import numpy as np

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])


In [10]:
print(arr.ndim)      # number of dimensions
print(arr.shape)    # (rows, cols)
print(arr.size)      # total elements
print(arr.dtype)     # data type


2
(2, 3)
6
int32


In [13]:
np.zeros((2, 3))
np.ones((3, 3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.arange(0, 10, 3)


array([0, 3, 6, 9])

In [19]:
np.linspace(0, 1, 5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [20]:
np.array([1, 2, 3], dtype=np.float32)


array([1., 2., 3.], dtype=float32)

In [21]:
arr = np.array([10, 20, 30, 40])


In [24]:
arr[0]        # 10
arr[-1]       # 40
arr[1:3]


array([20, 30])

In [25]:
print(arr[1:3])      # slicing

[20 30]


In [29]:
mat = np.array([[1,2,3],[4,5,6]])
mat[1, 2]     # 6
mat[:, 1]     # column
mat[0, :]     # row


array([1, 2, 3])

# Slices are views, not copies

In [31]:
a = np.array([1,2,3,4])
b = a[1:3]
b[0] = 99
print(a)

[ 1 99  3  4]


# To force copy:

In [39]:
ar=np.array([1,3,4,7])
br = ar[1:3].copy()
br[0] = 99
print(ar)

[1 3 4 7]


In [41]:
arr = np.array([1,2,3])
arr + 10
arr * 2
arr ** 2


array([1, 4, 9], dtype=int32)

In [42]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a + b


array([5, 7, 9])

# broadcasting

Rules (simplified):

Dimensions must align

Size 1 can expand

In [43]:
arr = np.array([[1,2,3],[4,5,6]])
arr + 10


array([[11, 12, 13],
       [14, 15, 16]])

In [44]:
arr + np.array([1, 0, -1])


array([[2, 2, 2],
       [5, 5, 5]])

In [47]:
brr=np.array([[1,2,3,4],[6,7,8,9]])

# Boolean Masking (POWER FEATURE)

In [51]:
brr[brr>2]

array([3, 4, 6, 7, 8, 9])

In [52]:
arr=[1,2,3,4,5,6]

In [58]:
np.sum(arr)
np.mean(arr)
np.min(arr)
np.max(arr)
np.std(arr)


1.707825127659933

In [63]:
#ELEMENT WISE:

np.sqrt(arr)
np.log(arr)
np.exp(arr)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 , 403.42879349])

In [67]:
arr = np.arange(6)
arr.reshape((3,2))


array([[0, 1],
       [2, 3],
       [4, 5]])

In [69]:
arr.T


array([0, 1, 2, 3, 4, 5])

In [77]:
a = np.array([1,2,9])
b = np.array([3,4,6])


In [80]:
np.vstack((a,b))
np.hstack((a,b))


array([1, 2, 9, 3, 4, 6])

# RANDOM  NUMBERS

In [84]:
np.random.rand(3)
np.random.randn(3)


array([-0.04653386, -1.19555259,  1.17935611])

In [86]:
np.random.randint(0, 10, size=5)


array([2, 8, 9, 1, 8])

In [92]:
np.random.rand(10)


array([0.9471375 , 0.63663796, 0.15266742, 0.75845797, 0.61722742,
       0.26757411, 0.56179498, 0.45720223, 0.70161692, 0.75847522,
       0.57719331, 0.0856982 , 0.78036187, 0.5314856 , 0.72043821,
       0.5580392 , 0.69451922, 0.026526  , 0.84706698, 0.98248476,
       0.92999867, 0.69769174, 0.65959888, 0.03551954, 0.94013369,
       0.48490236, 0.48828719, 0.49086197, 0.40915136, 0.95806119,
       0.26958887, 0.52281619, 0.55757403, 0.74218034, 0.32912193,
       0.34576288, 0.17643659, 0.56796217, 0.26237925, 0.28304463,
       0.7622272 , 0.46366083, 0.62067922, 0.22701941, 0.63289926,
       0.1948686 , 0.61654221, 0.04167137, 0.1790067 , 0.65561786,
       0.55680385, 0.13326481, 0.69757629, 0.86939794, 0.67811905,
       0.21827122, 0.84134813, 0.15498182, 0.8968313 , 0.73663422,
       0.87767498, 0.83101549, 0.62973929, 0.74591406, 0.90086676,
       0.75002433, 0.7703324 , 0.5801071 , 0.01414665, 0.40542951,
       0.38554048, 0.68838093, 0.67181815, 0.32107521, 0.73771

In [94]:
np.random.randn(10)


array([ 0.18467089, -0.96604887, -0.23051092,  0.01760693,  0.94060488,
       -1.36131534,  0.88088142, -0.36841574, -0.88515734,  0.07751579])

# rand- uniform distribution


In [135]:
np.random.rand()
np.random.uniform(m, n)
np.random.uniform(5, 10, size=5)    #size is no. of random values to generate, if no size then 1 value given
np.random.uniform(low=-1, high=1, size=(2, 3))

'''
np.random.uniform(a, b)
👉 It returns one random floating-point number drawn from a uniform distribution between:

css
Copy code
a  ≤  value  <  b
'''



NameError: name 'm' is not defined

# randn- normal distribution


In [116]:
np.random.randn()          # mean = 0, std = 1
np.random.normal(mean, std)


6.166726377545611